/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Hasan Emre
 */
public class HesapMakinasi extends javax.swing.JFrame {

    /**
     * Creates new form HesapMakinasi
     */
    public HesapMakinasi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new javax.swing.JLabel();
        label2 = new javax.swing.JLabel();
        label3 = new javax.swing.JLabel();
        Birinci_Sayi = new javax.swing.JTextField();
        Sonuc = new javax.swing.JTextField();
        ikinci_Sayi = new javax.swing.JTextField();
        Eksi = new javax.swing.JButton();
        arti = new javax.swing.JButton();
        Carpi = new javax.swing.JButton();
        Bolu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        label1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        label1.setText("Birinci Sayı: ");

        label2.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        label2.setText("İkinci Sayı: ");

        label3.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        label3.setText("Sonuc: ");

        Birinci_Sayi.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        Sonuc.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        ikinci_Sayi.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        Eksi.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Eksi.setText("-");
        Eksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EksiActionPerformed(evt);
            }
        });

        arti.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        arti.setText("+");
        arti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                artiActionPerformed(evt);
            }
        });

        Carpi.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Carpi.setText("x");
        Carpi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CarpiActionPerformed(evt);
            }
        });

        Bolu.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Bolu.setText("/");
        Bolu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoluActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Carpi)
                    .addComponent(arti)
                    .addComponent(label3)
                    .addComponent(label2)
                    .addComponent(label1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Birinci_Sayi, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                            .addComponent(ikinci_Sayi)
                            .addComponent(Sonuc)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Eksi)
                            .addComponent(Bolu))))
                .addContainerGap(204, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Birinci_Sayi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ikinci_Sayi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Sonuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Eksi)
                    .addComponent(arti))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Carpi)
                    .addComponent(Bolu))
                .addGap(75, 75, 75))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void artiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_artiActionPerformed
        
        int birinci_sayi = Integer.valueOf(this.Birinci_Sayi.getText());
        int ikinci_sayi = Integer.valueOf(this.ikinci_Sayi.getText());
        
        Sonuc.setText(String.valueOf(birinci_sayi+ikinci_sayi));
        
    }//GEN-LAST:event_artiActionPerformed

    private void EksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EksiActionPerformed
        int birinci_sayi = Integer.valueOf(this.Birinci_Sayi.getText());
        int ikinci_sayi = Integer.valueOf(this.ikinci_Sayi.getText());
        
        Sonuc.setText(String.valueOf(birinci_sayi-ikinci_sayi));
    }//GEN-LAST:event_EksiActionPerformed

    private void CarpiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CarpiActionPerformed
        int birinci_sayi = Integer.valueOf(this.Birinci_Sayi.getText());
        int ikinci_sayi = Integer.valueOf(this.ikinci_Sayi.getText());
        
        Sonuc.setText(String.valueOf(birinci_sayi*ikinci_sayi));

    }//GEN-LAST:event_CarpiActionPerformed

    private void BoluActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoluActionPerformed
        int birinci_sayi = Integer.valueOf(this.Birinci_Sayi.getText());
        int ikinci_sayi = Integer.valueOf(this.ikinci_Sayi.getText());
        
        Sonuc.setText(String.valueOf((double)birinci_sayi/ikinci_sayi));
    }//GEN-LAST:event_BoluActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HesapMakinasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HesapMakinasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HesapMakinasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HesapMakinasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HesapMakinasi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Birinci_Sayi;
    private javax.swing.JButton Bolu;
    private javax.swing.JButton Carpi;
    private javax.swing.JButton Eksi;
    private javax.swing.JTextField Sonuc;
    private javax.swing.JButton arti;
    private javax.swing.JTextField ikinci_Sayi;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel label3;
    // End of variables declaration//GEN-END:variables
}
