
import java.util.ArrayList;
import javax.swing.JOptionPane;




class user{
    
    private String kullanici_adi;
    private String parola;

    public user(String kullanici_adi, String parola) {
        this.kullanici_adi = kullanici_adi;
        this.parola = parola;
    }

    public String getKullanici_adi() {
        return kullanici_adi;
    }

    public void setKullanici_adi(String kullanici_adi) {
        this.kullanici_adi = kullanici_adi;
    }

    public String getParola() {
        return parola;
    }

    public void setParola(String parola) {
        this.parola = parola;
    }
    
    
}
public class AnaEkran extends javax.swing.JFrame {

    private static ArrayList<user> user_list = new ArrayList<user>();

    public static ArrayList<user> getUser_list() {
        return user_list;
    }

    public static void setUser_list(ArrayList<user> user_list) {
        AnaEkran.user_list = user_list;
    }
    
    
    
    
    public AnaEkran() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kullanici_alani = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        kullanici_girisi = new javax.swing.JTextField();
        parola_girisi = new javax.swing.JPasswordField();
        regester_alani = new javax.swing.JPanel();
        login_button = new javax.swing.JButton();
        register_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        kullanici_alani.setBackground(new java.awt.Color(51, 255, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel1.setText("KULLANICI ADI:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel2.setText("PAROLA:");

        kullanici_girisi.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        parola_girisi.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        javax.swing.GroupLayout kullanici_alaniLayout = new javax.swing.GroupLayout(kullanici_alani);
        kullanici_alani.setLayout(kullanici_alaniLayout);
        kullanici_alaniLayout.setHorizontalGroup(
            kullanici_alaniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kullanici_alaniLayout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addGroup(kullanici_alaniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(26, 26, 26)
                .addGroup(kullanici_alaniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(parola_girisi, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kullanici_girisi, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(166, Short.MAX_VALUE))
        );
        kullanici_alaniLayout.setVerticalGroup(
            kullanici_alaniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kullanici_alaniLayout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(kullanici_alaniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(kullanici_girisi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(kullanici_alaniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(parola_girisi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(189, Short.MAX_VALUE))
        );

        regester_alani.setBackground(new java.awt.Color(0, 102, 102));

        login_button.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        login_button.setText("Login");
        login_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_buttonActionPerformed(evt);
            }
        });

        register_button.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        register_button.setText("Register");
        register_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                register_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout regester_alaniLayout = new javax.swing.GroupLayout(regester_alani);
        regester_alani.setLayout(regester_alaniLayout);
        regester_alaniLayout.setHorizontalGroup(
            regester_alaniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, regester_alaniLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(login_button)
                .addGap(229, 229, 229))
            .addGroup(regester_alaniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(regester_alaniLayout.createSequentialGroup()
                    .addGap(168, 168, 168)
                    .addComponent(register_button)
                    .addContainerGap(469, Short.MAX_VALUE)))
        );
        regester_alaniLayout.setVerticalGroup(
            regester_alaniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(regester_alaniLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(login_button)
                .addContainerGap(59, Short.MAX_VALUE))
            .addGroup(regester_alaniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(regester_alaniLayout.createSequentialGroup()
                    .addGap(51, 51, 51)
                    .addComponent(register_button)
                    .addContainerGap(60, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kullanici_alani, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(regester_alani, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(kullanici_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(regester_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void register_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_register_buttonActionPerformed
        RegisterAlani registerAlani = new RegisterAlani();
        
        registerAlani.setVisible(true);
    }//GEN-LAST:event_register_buttonActionPerformed

    private void login_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_buttonActionPerformed
        
        String kullanici_adi = kullanici_girisi.getText();
        String parola = new String(parola_girisi.getPassword());
        
        if(user_list.size() == 0){
            JOptionPane.showMessageDialog(this, "Hiç kullanıcı bulunmamaktadır...");
        }
        else{
            for(user user : user_list){
                if((user.getKullanici_adi().equals(kullanici_adi)) &&  (user.getParola().equals(parola))){
                    JOptionPane.showMessageDialog(this, "Hoşgeldiniz " + kullanici_adi);
                }
                else{
                    JOptionPane.showMessageDialog(this, "Böyle bir kullanıcı bulunmamaktadır...\nLütfen register bölümünden kayıt olunuz.");
                }
            }
        }
        
    }//GEN-LAST:event_login_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnaEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnaEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnaEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnaEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AnaEkran().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel kullanici_alani;
    private javax.swing.JTextField kullanici_girisi;
    private javax.swing.JButton login_button;
    private javax.swing.JPasswordField parola_girisi;
    private javax.swing.JPanel regester_alani;
    private javax.swing.JButton register_button;
    // End of variables declaration//GEN-END:variables
}
