
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Hasan Emre
 */
public class StokUygulamasi extends javax.swing.JFrame {

    /**
     * Creates new form StokUygulamasi
     */
    public StokUygulamasi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        fiyatt = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        urun_ismi = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tahta = new javax.swing.JTable();
        yazi_alan = new javax.swing.JLabel();
        urun_ekle = new javax.swing.JButton();
        güncelle_butonu = new javax.swing.JButton();
        silme = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Ürün İsmi: ");

        jLabel2.setText("Katagori:");

        jLabel3.setText("Fiyat:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kültür Sanat", "Yemek", "Elektronik" }));

        tahta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ürün İsmi", "Katagori", "Fiyat"
            }
        ));
        tahta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tahtaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tahta);

        yazi_alan.setForeground(new java.awt.Color(255, 51, 51));

        urun_ekle.setText("Ürünü Ekle");
        urun_ekle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                urun_ekleActionPerformed(evt);
            }
        });

        güncelle_butonu.setText("Ürünleri Güncelle");
        güncelle_butonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                güncelle_butonuActionPerformed(evt);
            }
        });

        silme.setText("Ürün Silme");
        silme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                silmeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(140, 140, 140)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3))
                            .addGap(34, 34, 34)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jComboBox1, 0, 205, Short.MAX_VALUE)
                                .addComponent(fiyatt)
                                .addComponent(urun_ismi)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(103, 103, 103)
                            .addComponent(yazi_alan, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(urun_ekle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(güncelle_butonu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(silme, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(46, 46, 46))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(urun_ismi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(urun_ekle))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(güncelle_butonu))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(fiyatt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(silme))
                .addGap(18, 18, 18)
                .addComponent(yazi_alan, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void urun_ekleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_urun_ekleActionPerformed
        
       yazi_alan.setText("");
       DefaultTableModel model = (DefaultTableModel) tahta.getModel();
       
       if(urun_ismi.getText().trim().equals("")){
           
           yazi_alan.setText("Ürünün ismi boş bırakılmamalıdır...");
       }
       else{
           Object[] eklenecek = {urun_ismi.getText(),jComboBox1.getSelectedItem().toString(),fiyatt.getText()};
           model.addRow(eklenecek);
       }
        
       urun_ismi.setText("");
       fiyatt.setText("");
        
        
    }//GEN-LAST:event_urun_ekleActionPerformed

    private void güncelle_butonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_güncelle_butonuActionPerformed
        
        yazi_alan.setText("");
       DefaultTableModel model = (DefaultTableModel) tahta.getModel();
       
       int secili_row = tahta.getSelectedRow();
       
       if(secili_row == -1){
           
           if(tahta.getRowCount() == 0){
               yazi_alan.setText("Ürün tablosunda hiç bir ürün bulunmamaktadır...");
           }
           else{
               yazi_alan.setText("Seçili ürün bulunmamaktadır. Lütfen bir ürün seçiniz...");
           }
           
       }
       else{
           model.setValueAt(urun_ismi.getText(), secili_row, 0);
           model.setValueAt(jComboBox1.getSelectedItem().toString(), secili_row, 1);
           model.setValueAt(fiyatt.getText(), secili_row, 2);
           
           yazi_alan.setText("Ürün başarıyla gerçekleştirildi...");
       }
        
    }//GEN-LAST:event_güncelle_butonuActionPerformed

    private void tahtaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tahtaMouseClicked
        
        
        DefaultTableModel model = (DefaultTableModel)tahta.getModel();
        int secili_row = tahta.getSelectedRow();
        
        urun_ismi.setText(model.getValueAt(secili_row, 0).toString());
        jComboBox1.setSelectedItem(model.getValueAt(secili_row, 1).toString());
        fiyatt.setText(model.getValueAt(secili_row, 2).toString());
    }//GEN-LAST:event_tahtaMouseClicked

    private void silmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_silmeActionPerformed
        
        yazi_alan.setText("");
        
        DefaultTableModel model = (DefaultTableModel)tahta.getModel();
        
        int secili_row = tahta.getSelectedRow();
        
        if(secili_row == -1){
            
            if(tahta.getRowCount() == 0){
                yazi_alan.setText("Tabloda silinecek hiç bir ürün bulunmamaktadır...");
            }
            else{
                yazi_alan.setText("Seçili ürün bulunmamakatdır. Lütfen bir ürün seçiniz...");
            }
        }
        else{
            model.removeRow(secili_row);
            yazi_alan.setText("Ürün başarıyla silinmiştir...");
        }      
        
        
        
    }//GEN-LAST:event_silmeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StokUygulamasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StokUygulamasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StokUygulamasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StokUygulamasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StokUygulamasi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField fiyatt;
    private javax.swing.JButton güncelle_butonu;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton silme;
    private javax.swing.JTable tahta;
    private javax.swing.JButton urun_ekle;
    private javax.swing.JTextField urun_ismi;
    private javax.swing.JLabel yazi_alan;
    // End of variables declaration//GEN-END:variables
}
